spring:
  application:
    name: api-gateway
  profiles:
    default: local
  cloud:
    gateway:
      #      default-filters:
      #        - name: LoggingFilter
      #          args:
      #            baseMessage: "[OneLine]"
      #            preLogger: true
      #            postLogger: true
      routes:
        - id: alarm-service
          uri: lb://alarm-service
          predicates:
            - Path=/alarm/**
          filters:
            - RewritePath=alarm(?<segment>.*), $\{segment}
        - id: cafeteria-service
          uri: lb://cafeteria-service
          predicates:
            - Path=/cafeteria/**
          filters:
            - RewritePath=cafeteria(?<segment>.*), $\{segment}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
